{
 "title": "WAZUH - OVERVIEW",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "agent_name",
    "label": "Agent",
    "query": "{ \"find\": \"terms\", \"field\": \"agent.name\", \"query\": \"\"}"
   },
   {
    "name": "rule_level",
    "label": "Rule Level",
    "query": "{ \"find\": \"terms\", \"field\": \"rule.level\", \"query\": \"\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "CRITICA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.vulnerability.severity",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ALTA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.vulnerability.severity",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MEDIA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.vulnerability.severity",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "EVENTOS TOTAL",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:331",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:329", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent.name:$agent_name AND rule.level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ALERTAS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "rule.level:>=12 AND agent.name:$agent_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "GRAVIDADE (0 - 15)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rule.level",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "agent.name:$agent_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "DETALHE DOS ALERTAS",
   "type": "logs",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 3 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "250" }, "type": "logs" }
     ],
     "query": "agent.name:$agent_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "AGENTS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:235",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "365d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:233",
       "field": "agent.name",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "agent.name:$agent_name AND rule.level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ALERTAS POR CATEGORIA",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "rule.groups",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "rule.level:>=12 AND agent.name:$agent_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ALERTA POR AGENTES",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "agent.name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "rule.level:>=12 AND agent.name:$agent_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTOS DE SEGURANÇA POR NÍVEL DE ALERTA",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:235",
       "fake": true,
       "field": "rule.level",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:236",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:233",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "agent.name:$agent_name AND rule.level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTOS DE SEGURANÇA POR NÍVEL DE ALERTA",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:235",
       "fake": true,
       "field": "agent.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:236",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:233",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "agent.name:$agent_name AND rule.level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "GRAVIDADE DOS EVENTOS - HISTÓRICO",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.level",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.name:$agent_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VULNERABILIDADE POR LVL",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "LVL : 15",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule.level:15",
     "timeField": "@timestamp"
    },
    {
     "alias": "LVL :  12-14",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule.level:[12 TO 14]",
     "timeField": "@timestamp"
    },
    {
     "alias": "LVL :  6-11",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule.level:[6 TO 11]",
     "timeField": "@timestamp"
    },
    {
     "alias": "LVL :  4-6",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule.level:[4 TO 6]",
     "timeField": "@timestamp"
    },
    {
     "alias": "LVL :  1-3",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule.level:[1 TO 3]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "EVENTOS",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "250" }, "type": "raw_data" }
     ],
     "query": "agent.name:$agent_name AND rule.level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}