{
 "title": "Wazuh - Servidor",
 "description": "Grafana Dashboard - Wazuh SIEM XDR - v4.8.0",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "VM - Graphics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "01- Linux servers" },
     "host": { "filter": "CC-SV106 - SIEM" },
     "item": { "filter": "CPU utilization" },
     "itemTag": { "filter": "component: cpu" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "01- Linux servers" },
     "host": { "filter": "CC-SV106 - SIEM" },
     "item": { "filter": "FS [/]: Space: Used, in %" },
     "itemTag": { "filter": "component: storage" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Network Interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 1 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "01- Linux servers" },
     "host": { "filter": "CC-SV106 - SIEM" },
     "item": {
      "filter": "Interface ens160: Bits received"
     },
     "itemTag": { "filter": "interface: ens160" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "01- Linux servers" },
     "host": { "filter": "CC-SV106 - SIEM" },
     "item": { "filter": "Interface ens160: Bits sent" },
     "itemTag": { "filter": "interface: ens160" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Event for Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Number Process",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "01- Linux servers" },
     "host": { "filter": "CC-SV106 - SIEM" },
     "item": { "filter": "Number of processes" },
     "itemTag": { "filter": "component: system" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Memory RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "01- Linux servers" },
     "host": { "filter": "CC-SV106 - SIEM" },
     "item": { "filter": "Memory utilization" },
     "itemTag": { "filter": "component: memory" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Disk Free Space GB",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "01- Linux servers" },
     "host": { "filter": "CC-SV106 - SIEM" },
     "item": { "filter": "FS [/]: Space: Available" },
     "itemTag": { "filter": "component: storage" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Users Logged",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "01- Linux servers" },
     "host": { "filter": "CC-SV106 - SIEM" },
     "item": { "filter": "Number of logged in users" },
     "itemTag": { "filter": "component: environment" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  { "title": "Compliance and Frameworks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Vulnerability LVL",
   "type": "timeseries",
   "description": "Vulnerability LVL",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "LVL : 15",
     "bucketAggs": [
      { "field": "@timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "rule.level:15",
     "timeField": "@timestamp"
    },
    {
     "alias": "LVL :  12-14",
     "bucketAggs": [
      { "field": "@timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "rule.level:[12 TO 14]",
     "timeField": "@timestamp"
    },
    {
     "alias": "LVL :  6-11",
     "bucketAggs": [
      { "field": "@timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "rule.level:[6 TO 11]",
     "timeField": "@timestamp"
    },
    {
     "alias": "LVL :  4-6",
     "bucketAggs": [
      { "field": "@timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "rule.level:[4 TO 6]",
     "timeField": "@timestamp"
    },
    {
     "alias": "LVL :  1-3",
     "bucketAggs": [
      { "field": "@timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "rule.level:[1 TO 3]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Fortigate - Count",
   "type": "timeseries",
   "description": "Fortigate - Count",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Fortigate",
     "bucketAggs": [
      { "field": "@timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "fortigate",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Mitre ID",
   "type": "piechart",
   "description": "Mitre ID",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.mitre.id",
       "id": "7",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GDPR",
   "type": "piechart",
   "description": "GDPR",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.gdpr",
       "id": "7",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Rules Groups",
   "type": "piechart",
   "description": "Rules Groups",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.groups",
       "id": "7",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "NIST 800.53 Agent Count",
   "type": "piechart",
   "description": "NIST 800.53 Agent Count",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.nist_800_53",
       "id": "7",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Mitre Tactic",
   "type": "piechart",
   "description": "Mitre Tactic",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.mitre.tactic",
       "id": "7",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Office 365 - Table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Office 365 - Users",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.id",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data.office365.Actor.ID",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "data.office365.Actor.Type",
       "id": "1",
       "meta": {
        "count": true,
        "std_deviation_bounds_lower": false,
        "std_deviation_bounds_upper": false
       },
       "type": "extended_stats"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "All Rules - Count",
   "type": "table",
   "description": "All Rules - Count",
   "gridPos": { "h": 12, "w": 12, "x": 6, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.id",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "rule.description",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Office 365 - Users Critical",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.id",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data.office365.Recipients",
       "id": "7",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Office Rules Level - Count",
   "type": "table",
   "description": "Office Rules Level - Count",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.id",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data.office365.ClientIP",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "field": "rule.level",
       "id": "9",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "data.office365.UserId",
       "id": "10",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Office 365 - Logon",
   "type": "table",
   "description": "Office 365 - Logon",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.office365.Actor.ID",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data.office365.ClientIP",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Fortigate - Rules", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Fortigate - Count",
   "type": "table",
   "description": "Fortigate - Count",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.srcuser",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "data.srcip",
       "id": "8",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "data.transip",
       "id": "9",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "data.url",
       "id": "10",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "data.dstip",
       "id": "11",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Fortigate - Count",
   "type": "table",
   "description": "Fortigate - Count",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.srcuser",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "data.srcip",
       "id": "8",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "data.transip",
       "id": "9",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "data.url",
       "id": "10",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "data.dstip",
       "id": "11",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}